[workspace]
resolver = "2"
members = ["crates/levoc", "crates/levo-lex"]

[workspace.package]
authors = ["Ahraman"]
edition = "2021"
rust-version = "1.81.0"
repository = "https://github.com/LevoLang/levo-compiler"
readme = "README.md"
license-file = "LICENSE"
description = """
A compiler for the Levo programming language written in Rust.
"""
keywords = ["compiler", "levo"]
categories = ["compilers"]
